### PR TITLE
Release Candidate 0.24.4

### PR DESCRIPTION
**Pull request by arddluma**
Production Release Version 0.24.4

A rollup release of all changes from develop to master branch.

Features:
- Added UI toggles on the widget for developers
- Added a Mainnet/Testnet toggle
- Enabled OKX Chain

Fixes:
- UI fixes across the widget
- Fixed dynamic gas for Klima Staking
- Fixed logo sources
- Wallet now opens if there's no other block

### CODE REVIEW

**Review by MayukhSamadder2000 — APPROVED** [review]
LGTM

**Review by parag-chauhan — APPROVED** [review]
LGTM

**Review by vignesha22 — APPROVED** [review]
LGTM. Just one thing on the format, please see to it that the files are ended with a new line.

**Review by Yash-Chaubal — APPROVED** [review]
LGTM!

**Pull request merged**
